global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: mongooseim
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:4445']
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'
